# Generated by Django 5.2 on 2025-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expdate', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_sm',
            field=models.BooleanField(default=False, verbose_name='Quản lý nhóm (is_sm)'),
        ),
    ]
