# Generated by Django 5.2 on 2025-05-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expdate', '0003_alter_userprofile_is_sm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmail'),
        ),
    ]
